apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "branch-cups.fullname" . }}-config
  labels:
    {{- include "branch-cups.labels" . | nindent 4 }}
data:
  cupsd.conf: |
{{ .Values.cupsConfig | indent 4 }}
